config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'posts#index'

  resources :posts do
    resources :comments, only: :create
  end

  
  resources :users do
    resource :follow
    resources :followings
    resources :followers
  end

  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :text, presence: true, length: { maximum: 200 }
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user
  belongs_to :target_user, class_name: 'User', foreign_key: 'target_user_id'

  validates :target_user_id, uniqueness: { scope: :user_id }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :post_image
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true
  validates :post_image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         validates :email,           format: { with: /@/}, on: :create
         validates :password,        length: { minimum: 6 }, confirmation: true,  format: { with: /\A[a-zA-Z0-9]+\z/ }, on: :create
       
         validates :name, presence: true
         validates :profile, presence: true
         has_one_attached :user_image   

         has_many :posts, dependent: :destroy
         has_many :comments, dependent: :destroy
         has_many :likes, dependent: :destroy
         has_many :active_relationships, class_name: 'Follow', foreign_key: 'user_id', dependent: :destroy
         has_many :passive_relationships, class_name: 'Follow', foreign_key: 'target_user_id', dependent: :destroy
         has_many :followings, through: :active_relationships, source: :target_user
         has_many :followers, through: :passive_relationships, source: :user
         
         def liked_by?(post_id)
          likes.where(post_id: post_id).exists?
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to post_path(@comment.post)
    else
      @post = @comment.post
      @comments = @post.comments
      render "posts/show"
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  def index
    @followers = User.find(params[:user_id]).followers
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  def index
    @followings = User.find(params[:user_id]).followings
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!

  def create
    current_user.active_relationships.create(target_user_id: params[:user_id])

    redirect_to [:user, { id: params[:user_id] }]
  end

  def destroy
    current_user.active_relationships.find_by(target_user_id: params[:user_id]).destroy

    redirect_to [:user, { id: params[:user_id] }]
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :post_params

  def create
    Like.create(user_id: current_user.id, post_id: params[:id])
  end

  def destroy
    Like.find_by(user_id: current_user.id, post_id: params[:id]).destroy
  end

  private

  def post_params
    @post = Post.find(params[:id])
  end
 
 end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.includes(:user)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.valid?
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def edit
    if @post.user != current_user
      redirect_to root_path
    end
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post.id), method: :get
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end


  def set_post
    @post = Post.find(params[:id])
  end

  private
  def post_params
    params.require(:post).permit(:title, :post_image).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, only: [:show]
  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
        redirect_to user_path(current_user), alert: "不正なアクセスです。"
    end
  end

  def update
    @user = User.find(params[:id])
    @user.valid?
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "ユーザー情報を更新しました。"
    else
      render :edit
    end
  end

  def destroy 
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :user_image, :profile)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/followers/index.html.erb
<div class="main_form">
  <div class="followers">
    <% @followers.each do |user| %>
      <div class="follower_icon">
        <div class='user_image_follow'>
          <% if user.user_image.attached? %>
            <%= image_tag user.user_image , class: "user_image_follows"%> 
          <% else %>
            <%= image_tag ( "photo.jpg") , class: "user_image_follows" %> 
          <% end%>
          <div class="follower_name">
            <%= link_to user.name, [user] %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/followings/index.html.erb
<div class="main_form">
  <div class="followers">
   <% @followings.each do |user| %>
      <div class="follower_icon">
        <div class='user_image_follow'>
          <% if user.user_image.attached? %>
            <%= image_tag user.user_image , class: "user_image_follows"%> 
          <% else %>
            <%= image_tag ( "photo.jpg") , class: "user_image_follows" %> 
          <% end%>
          <div class="follower_name">
            <%= link_to user.name, [user] %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/likes/create.js.erb
document.getElementById('post_<%= @post.id %>').innerHTML = '<%= j(render @post) %>'

app/views/likes/destroy.js.erb
document.getElementById('post_<%= @post.id %>').innerHTML = '<%= j(render @post) %>'

app/views/posts/_form.html.erb
<div class="form">
  <div class="field">
    <%= form_with(model: @post,local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="image_form">
        <div class="image_preview", id="image-list"></div>
        <% if @post.post_image.attached? %>
          <%= image_tag @post.post_image , class: "photo"%> 
        <% else %>
          <%= image_tag 'photo.jpg',class: "photo" %>
        <% end%>
       <%= f.file_field :post_image %> 
        <div class="text_field">
          <%= f.text_area :title ,placeholder:"オプションを記入" %>
        </div>
      </div>
      <div class="action_form">
        <div class="actions">
          <%= button_to "キャンセル", {controller: 'posts', action: 'index'}, {method: :get} %>
        </div>
        <div class="actions">
          <%= f.submit "  送  信  " %>
        </div>
      </div>
     <% end %>
  </div>
</div>

app/views/posts/_post.html.erb
<% if user_signed_in?%>
  <% if current_user.liked_by?(post.id) %>
    <div>
      <%= link_to destroy_like_path(post), class: "like-link", method: :DELETE, remote: true do %>
        <i class="fa fa-heart unlike-btn"></i>
      <% end %>
      <%= post.likes.count %>
    </div>
  <% else %>
    <div>
      <%= link_to create_like_path(post), class: "like-link", method: :POST, remote: true do %>
        <i class="fa fa-heart like-btn"></i>
      <% end %>
      <%= post.likes.count %>
    </div>
  <% end %>
<% end %>

app/views/posts/edit.html.erb
 <div class="main_form">
   <%= render partial: "form" , locals:{ post: @post } %>
 </div>

app/views/posts/index.html.erb
<div class="main"><%= link_to image_tag("top.jpg", class: :logo), root_path %>
  <div class="inner">
    <div class="post-contents">
        <% @posts.each do |post| %>
          <div class="post-content">
            <div class="post_body">
              <div class='image_content'>
                <%= link_to (image_tag post.post_image), post_path(post.id), method: :get, class: "post_image"%>
              </div>
            </div>
            <div class="text_form">
                <%= link_to post.title, post_path(post.id), method: :get, class: :post_title%>
                <div class="like", id="post_<%= post.id %>">
                  <% if user_signed_in?%>
                    <% if current_user.liked_by?(post.id) %>
                      <div>
                        <%= link_to destroy_like_path(post), class: "like-link", method: :DELETE, remote: true do %>
                        <i class="fa fa-heart unlike-btn"></i>
                        <% end %>
                        <%= post.likes.count %>
                      </div>
                    <% else %>
                      <div>
                        <%= link_to create_like_path(post), class: "like-link", method: :POST, remote: true do %>
                        <i class="fa fa-heart like-btn"></i>
                        <% end %>
                        <%= post.likes.count %>
                      </div>
                    <% end %>
                  <% end %>
                </div>
            </div>
            <div class="user_form_index">
              <div class="user_image_index">
                <% if post.user.user_image.attached? %>
                  <%= image_tag post.user.user_image , class: "user_image_index"%> 
                <% else %>
                  <%= image_tag ( "photo.jpg") , class: "user_image_index" %> 
                <% end%>
              </div>
              <div class="users_name">
                <%= link_to post.user.name, user_path(post.user.id), method: :get, class: :card__title%>
              </div>
            </div>
          </div> 
        <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
 <div class="main_form">
   <%= render partial: "form" , locals:{ post: @post } %>
 </div>

app/views/posts/show.html.erb
<div class="main_form">  
  <div class="form">
    <div class="more">
      <% if user_signed_in? && current_user.id == @post.user_id %>
        <ul class="global_menu">
          <li><a class="navber" ,href="#"><%= image_tag 'nav-top.png' ,class: "nav_image"%></a>
            <ul>
              <li><%= link_to "編集する", edit_post_path(@post.id), method: :get, class: :pull_down_list %></li>
              <li><%= link_to "削除する", post_path, method: :delete, class: :pull_down_list %></li>
            </ul>
          </li>
        </ul>
      <% end %>
    </div> 
    <div class="image">
      <div id="image-list"></div>
      <%= image_tag @post.post_image, class: "post_show"  %>
      <div class="post_user_name">
        <%= @post.user.name%>
      </div>
      <div class="text_field">
        <%=  @post.title %>
      </div>
      </div>
      <div class="comments">
        <% if user_signed_in?%>
          <%= form_with(model: [@post, @comment], local: true) do |f| %>
            <%= render 'layouts/error_messages', model: f.object %>
            <div class="text_field">
              <%= f.label :text, "コメント" %>
              <%= f.text_field :text %>
              <%= f.submit '投稿する' , id: "submit" %>
            </div>
          <% end %> 
        <% end %>        
        <div class="comment_forms">
          <% if @comments %>
            <% @comments.each do |comment| %>
              <div class="comment_form">
                <%# <%= link_to attachment_image_tag(comment.user, :user_image, class: "user_images", fallback:"photo.jpg"), user_path(comment.user.id)%> %>
                <div class="user_name_form">
                  <%# <%= link_to comment.user.name, user_path(comment.user.id), class: :comment_user %> %>
                </div>
                <div class="comment_texts">
                  <%= comment.text %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div> 
      </div>
    
  </div>
</div>

app/views/users/edit.html.erb
<div class="main_form">
  <div class="main">
    <div class="inner">
      <%= form_with(model: @user, local: true) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        <div class="user_back">
          <div class='users_form_edit'>
            <div class='image_user_form'>
            <div class="image_preview_user", id="image-list"></div>
            <% if @user.user_image.attached? %>
              <%= image_tag @user.user_image , class: "photo_user"%> 
            <% else %>
              <%= image_tag ( "photo.jpg") , class: "photo_user" %> 
            <% end%>
            </div>
      　　　　 <%= f.file_field :user_image %> 
          </div>  
        </div>
        <div class="user_texts">
          <div class="user_name_edit">
            <%= f.text_field :name, autofocus: true%>
          </div>
          <div class="user_profiles_edit">
            <%= f.text_field :profile, class: "profile_edit"%>
          </div>
        </div>
        <div class="button_form_edit">
          <div class='button_update'>
            <%= f.submit "update", class: 'btn_update'%>
          </div>
          <div class='button_delete'>
            <%=link_to user_path(current_user.id), method: :delete  do %>
              <%= f.submit "Delete", class: 'btn_delete'%>
            <%end%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="main_form">
  <div class="main">
    <div class="inner">
      <div class="user__wrapper">
        <div class="page-heading">
          <div class="user_names"><%= @user.name%></div>
        </div>
        <div class='user-form'>
          <div class='user_image'>
            <% if @user.user_image.attached? %>
              <%= image_tag @user.user_image , class: "user_image"%> 
            <% else %>
              <%= image_tag ( "photo.jpg") , class: "user_image" %> 
            <% end%>
          </div>
          <div class="user-form-side">
            <div class="user-forms">
              <div class="user_format">
                <div class="format_button">
                  <div class="count"><%= @posts.count%></div>
                  <p>投稿</p>
                </div>
                <div class="format_button">
                  <div class="count"> <%= @user.followings.count %></div>
                  <p><%= link_to "フォロー中", [@user, :followings] %></p>
                </div>
                <div class="format_button">
                  <div class="count"><%=@user.followers.count %></div>
                  <p><%= link_to "フォロワー", [@user, :followers] %></p>
                </div>
              </div>
            </div>
            <div class="user_profile">
              <div class="user_profiles">
                <%= @user.profile %>
              </div>
              <div class="follows">
                <%if user_signed_in? && current_user != @user %>
                  <% if current_user.active_relationships.exists?(target_user_id: @user.id) %>
                    <%= link_to 'unfollow', [@user, :follow], method: :delete, class: :unfollow %>
                  <% else %>
                    <%= link_to 'follow', [@user, :follow], method: :post, class: :follow %>
                  <% end %>
                <% else%>
                  <%= link_to "プロフィールを編集", edit_user_path(current_user), class: :edit_button %>
                <% end %>
              </div>  
            </div>
          </div>
        </div>
      </div>
      <div class="user-post">
        <div class="`user_post-contents">
          <% @posts.each do |post| %>
            <div class="post-content">
            <div class="post_body">
              <div class='image_content'>
                <%= link_to (image_tag post.post_image), post_path(post.id), method: :get, class: "post_image"%>
              </div>
            </div>
            <div class="text_form">
                <%= link_to post.title, post_path(post.id), method: :get, class: :post_title%>
                <div class="like", id="post_<%= post.id %>">
                  <% if user_signed_in?%>
                    <% if current_user.liked_by?(post.id) %>
                      <div>
                        <%= link_to destroy_like_path(post), class: "like-link", method: :DELETE, remote: true do %>
                        <i class="fa fa-heart unlike-btn"></i>
                        <% end %>
                        <%= post.likes.count %>
                      </div>
                    <% else %>
                      <div>
                        <%= link_to create_like_path(post), class: "like-link", method: :POST, remote: true do %>
                        <i class="fa fa-heart like-btn"></i>
                        <% end %>
                        <%= post.likes.count %>
                      </div>
                    <% end %>
                  <% end %>
                </div>
            </div>
          </div> 
          <% end %>
        </div>
      </div>  
    </div>
  </div>
</div>